{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fix_categorical_columns",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Διόρθωση categorical στηλών - One Hot Encoding\n",
    "\n",
    "print(\"Διόρθωση categorical στηλών για μοντελοποίηση...\")\n",
    "print(\"=\"*50)\n",
    "\n",
    "# Έλεγχος για categorical στήλες\n",
    "categorical_columns = X_train.select_dtypes(include=['object']).columns\n",
    "print(f\"Βρέθηκαν {len(categorical_columns)} categorical στήλες:\")\n",
    "for col in categorical_columns:\n",
    "    print(f\"   - {col}\")\n",
    "    print(f\"     Μοναδικές τιμές: {X_train[col].unique()}\")\n",
    "\n",
    "# One Hot Encoding για categorical στήλες\n",
    "X_train_encoded = pd.get_dummies(X_train, columns=categorical_columns, drop_first=True)\n",
    "X_val_encoded = pd.get_dummies(X_val, columns=categorical_columns, drop_first=True)\n",
    "X_test_encoded = pd.get_dummies(X_test, columns=categorical_columns, drop_first=True)\n",
    "\n",
    "# Βεβαιωση ότι όλα τα sets έχουν τις ίδιες στήλες\n",
    "all_columns = set(X_train_encoded.columns) | set(X_val_encoded.columns) | set(X_test_encoded.columns)\n",
    "\n",
    "for col in all_columns:\n",
    "    if col not in X_train_encoded.columns:\n",
    "        X_train_encoded[col] = 0\n",
    "    if col not in X_val_encoded.columns:\n",
    "        X_val_encoded[col] = 0\n",
    "    if col not in X_test_encoded.columns:\n",
    "        X_test_encoded[col] = 0\n",
    "\n",
    "# Ταξινόμηση στηλών για consistency\n",
    "X_train_encoded = X_train_encoded[sorted(all_columns)]\n",
    "X_val_encoded = X_val_encoded[sorted(all_columns)]\n",
    "X_test_encoded = X_test_encoded[sorted(all_columns)]\n",
    "\n",
    "print(f\"\\nΜετά το one-hot encoding:\")\n",
    "print(f\"Train set: {X_train_encoded.shape}\")\n",
    "print(f\"Validation set: {X_val_encoded.shape}\")\n",
    "print(f\"Test set: {X_test_encoded.shape}\")\n",
    "print(f\"Νέα χαρακτηριστικά: +{X_train_encoded.shape[1] - X_train.shape[1]}\")\n",
    "\n",
    "# Αντικατάσταση των παλιών με τα νέα\n",
    "X_train = X_train_encoded\n",
    "X_val = X_val_encoded\n",
    "X_test = X_test_encoded\n",
    "\n",
    "print(\"\\n✅ Οι categorical στήλες μετατράπηκαν με επιτυχία!\")\n",
    "print(\"🚀 Τα δεδομένα είναι έτοιμα για μοντελοποίηση!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "feature_analysis_fixed",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Γρήγορη ανάλυση χαρακτηριστικών (διορθωμένη έκδοση)\n",
    "\n",
    "print(\"Ανάλυση Χαρακτηριστικών:\")\n",
    "print(\"=\"*50)\n",
    "\n",
    "# Βασικά στατιστικά για τα χαρακτηριστικά\n",
    "print(f\"\\nΣτατιστικά Training Χαρακτηριστικών:\")\n",
    "print(f\"   Συνολικά χαρακτηριστικά: {X_train.shape[1]}\")\n",
    "print(f\"   Συνολικά δείγματα: {X_train.shape[0]}\")\n",
    "print(f\"   Ελλιπείς τιμές: {X_train.isnull().sum().sum()}\")\n",
    "print(f\"   Τύποι δεδομένων: {X_train.dtypes.nunique()} μοναδικοί τύποι\")\n",
    "\n",
    "# Έλεγχος για ακραίες τιμές στα κανονικοποιημένα δεδομένα\n",
    "extreme_values = (np.abs(X_train) > 3).sum().sum()\n",
    "print(f\"   Ακραίες τιμές (>3 std): {extreme_values}\")\n",
    "\n",
    "# Top 10 χαρακτηριστικά με τη μεγαλύτερη διακύμανση\n",
    "feature_variances = X_train.var().sort_values(ascending=False)\n",
    "print(f\"\\nTop 10 Χαρακτηριστικά με βάση τη Διακύμανση:\")\n",
    "for i, (feature, variance) in enumerate(feature_variances.head(10).items(), 1):\n",
    "    print(f\"   {i:2d}. {feature}: {variance:.4f}\")\n",
    "\n",
    "# Οπτικοποίηση διακύμανσης\n",
    "plt.figure(figsize=(12, 6))\n",
    "top_features = feature_variances.head(15)\n",
    "bars = plt.barh(range(len(top_features)), top_features.values)\n",
    "plt.yticks(range(len(top_features)), top_features.index)\n",
    "plt.xlabel('Διακύμανση')\n",
    "plt.title('Top 15 Χαρακτηριστικά με βάση τη Διακύμανση', fontsize=14, fontweight='bold')\n",
    "plt.gca().invert_yaxis()\n",
    "\n",
    "# Προσθήκη χρωμάτων\n",
    "colors = plt.cm.viridis(np.linspace(0, 1, len(bars)))\n",
    "for bar, color in zip(bars, colors):\n",
    "    bar.set_color(color)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "print(\"\\nΗ ανάλυση χαρακτηριστικών ολοκληρώθηκε!\")\n",
    "print(\"Τα δεδομένα είναι έτοιμα για μοντελοποίηση ταξινόμησης!\")"
   ]
  }
 ],
 "metadata": {},
 "nbformat": 4,
 "nbformat_minor": 5
}
